name: Test URL Access

on:
  push:
    branches:
      - main

jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test URL access for code.visualstudio.com
        run: |
          n=0
          success=false
          until [ $n -ge 5 ]
          do
            if curl -o /dev/null -sf https://code.visualstudio.com/api/working-with-extensions/bundling-extension; then
              success=true
              break
            fi
            n=$((n+1))
            sleep 10
          done
          if [ "$success" = false ]; then
            echo "Failed to access https://code.visualstudio.com/api/working-with-extensions/bundling-extension after 5 attempts"
            exit 1
          else
            echo "Successfully accessed https://code.visualstudio.com/api/working-with-extensions/bundling-extension"
          fi
      
      - name: Test URL access for techcommunity.microsoft.com
        run: |
          n=0
          success=false
          until [ $n -ge 5 ]
          do
            if curl -o /dev/null -sf https://techcommunity.microsoft.com/t5/educator-developer-blog/fine-tune-and-integrate-custom-phi-3-models-with-prompt-flow-in/ba-p/4191726?wt.mc_id=studentamb_279723; then
              success=true
              break
            fi
            n=$((n+1))
            sleep 10
          done
          if [ "$success" = false ]; then
            echo "Failed to access https://techcommunity.microsoft.com/t5/educator-developer-blog/fine-tune-and-integrate-custom-phi-3-models-with-prompt-flow-in/ba-p/4191726?wt.mc_id=studentamb_279723 after 5 attempts"
            exit 1
          else
            echo "Successfully accessed https://techcommunity.microsoft.com/t5/educator-developer-blog/fine-tune-and-integrate-custom-phi-3-models-with-prompt-flow-in/ba-p/4191726?wt.mc_id=studentamb_279723"
          fi
